name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Revisa el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instala Flutter con una versión específica
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5' # Versión exacta de Flutter
          architecture: x64

      # Verifica la instalación de Flutter
      - name: Verify Flutter installation
        run: flutter doctor

      # Instala dependencias de Flutter
      - name: Install dependencies
        run: flutter pub get

      # Construye la app para web
      - name: Build Flutter Web
        run: flutter build web --release

      # Despliega en Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_APPENITAXIUSUARIOS }}
          channelId: live
          projectId: appenitaxiusuarios
